# Generated by Django 4.0.4 on 2024-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_line_1_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
